import React from 'react'
import RewardsStyle from './Rewards.style'
import SectionTitle from '../../../Core/SectionTitle/SectionTitle'

import rewardsImage from '../../../../assets/images/img/rewards-img.png'
import rewardsShape from '../../../../assets/images/shape/rewards-shape.png'
import cursorIcon from '../../../../assets/images/icon/cursor.png'
import ScrollAnimate from '../../../Core/ScrollAnimate'

const Rewards = () => {
    return (
        <RewardsStyle>
            <div className="container">
                <div className="row flex-row-reverse">
                    <div className="col-lg-6">
                        <ScrollAnimate delay={300}>
                            <div className="rewards-right">
                                <SectionTitle title="The Minaris Pools — Win While You Evolve" />
                                <h6>Stake your $DRPEPE to activate the Minari Pool and unlock:</h6>
                                <ul>
                                    <li><img src={cursorIcon} alt="icon" /> AI-driven return strategies</li>
                                    <li><img src={cursorIcon} alt="icon" /> Improvements for your Minaris</li>
                                    <li><img src={cursorIcon} alt="icon" /> Rewards based on your commitment and performance</li>
                                </ul>
                                <p className=''>Part of the revenue generated by subscriptions and AI services is returned to the stakers, creating a  virtuous circle: <br />
                                    <span>use → improve → reward.</span></p>
                                <p className=''>The more the network works, the more the network earns.</p>
                                <button className="primary-btn rewards-btn hover-btn">
                                    <span className="btn-text">
                                        <span>Get Rewards Now!</span>
                                        <span>Get Rewards Now!</span>
                                    </span>
                                </button>
                            </div>
                        </ScrollAnimate>
                    </div>
                    
                    <div className="col-lg-6">
                        <ScrollAnimate delay={200}>
                            <div className="rewards-left">
                                <div className="rewards-img">
                                    <img src={rewardsShape} alt="shape" className='blur-shape' />
                                    <img src={rewardsImage} alt="icon" />
                                </div>
                            </div>
                        </ScrollAnimate>
                    </div>

                </div>
            </div>
        </RewardsStyle>
    )
}

export default Rewards